import { Project } from '@/types';

export const PROJECTS: Project[] = [
  {
    slug: 'soma-health',
    name: 'Soma Health',
    url: 'https://somahealthapp.netlify.app/',
    tagline: 'Bridging patients and providers through digital infrastructure.',
    tags: ['HEALTH-TECH', 'SAAS', 'PATIENT PORTAL'],
    desc: 'A comprehensive healthcare management platform designed to streamline communication between patients and providers.',
    challenge: 'The client needed a HIPAA-compliant platform simultaneously intuitive for elderly patients and powerful for clinical staff. Legacy systems were fragmented across 3 different tools.',
    solution: 'A unified portal with role-based dashboards — a simplified patient-facing UI and a feature-rich clinician dashboard. Built on Next.js with a secure Node.js backend.',
    results: ['40% reduction in appointment no-shows', 'Staff admin time cut by 6 hours/week', '94% patient satisfaction in first 3 months'],
    tech: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    year: '2024',
    category: 'Web Application',
    color: '#0a4a3a',
    hasDoc: true,
  },
  {
    slug: 'chic-fashion',
    name: 'Chic Fashion House',
    url: 'https://chicfashionhouse.netlify.app/',
    tagline: 'Visual storytelling for a luxury clothing brand.',
    tags: ['E-COMMERCE', 'UI/UX'],
    desc: 'A stylish e-commerce platform for high-end clothing collections, focusing on visual storytelling and an immersive brand experience.',
    challenge: 'The brand had a strong offline presence but a dated website that failed to communicate their luxury positioning. Conversion rates were under 1%.',
    solution: 'Full redesign with editorial-style product pages, a custom collection showcase, and a streamlined 3-step checkout. Photography-first layout.',
    results: ['Conversion rate improved from 0.8% to 3.4%', 'Average order value increased by 22%', 'Bounce rate dropped from 68% to 41%'],
    tech: ['Next.js', 'Shopify API', 'Framer Motion', 'Sanity CMS'],
    year: '2024',
    category: 'E-Commerce',
    color: '#2a1a0a',
  },
  {
    slug: 'velora-airlines',
    name: 'Velora Airlines',
    url: 'https://veloraairlines.netlify.app/',
    tagline: 'A booking experience as smooth as the flight.',
    tags: ['BOOKING SYSTEM', 'JAVASCRIPT', 'UI/UX'],
    desc: 'A complex flight booking interface emphasising user flow, speed, and clarity across a multi-step reservation process.',
    challenge: 'Airline booking flows are notoriously complex. The goal was to reduce time-to-booking and eliminate cognitive overload.',
    solution: 'A linear step-by-step flow with persistent progress tracking, smart defaults, and real-time seat visualisation.',
    results: ['Booking completion rate up 28%', 'Average time-to-book under 4 minutes', 'Mobile bookings increased by 55%'],
    tech: ['JavaScript', 'CSS3', 'HTML5', 'REST APIs'],
    year: '2023',
    category: 'Web Application',
    color: '#0a1a3a',
  },
  {
    slug: 'la-belle',
    name: 'La Belle Cuisine',
    url: 'https://labellecuisine.netlify.app/',
    tagline: 'Where food meets editorial design.',
    tags: ['CULINARY', 'RESPONSIVE', 'CMS'],
    desc: 'A recipe and menu showcase with clean typography and appetising layout structures for a high-end culinary brand.',
    challenge: 'The client wanted a site as refined as their food. They also needed staff to update menus without a developer.',
    solution: 'Editorial-style layout with a custom Sanity CMS integration. Full responsive design with print-optimised recipe pages.',
    results: ['Table reservations up 35% in first month', 'Staff update menus in under 5 minutes', 'Featured in 2 local food publications'],
    tech: ['Next.js', 'Sanity CMS', 'Tailwind CSS', 'Vercel'],
    year: '2023',
    category: 'Website',
    color: '#1a0a0a',
  },
  {
    slug: 'luxeestates',
    name: 'Luxeestates',
    url: 'https://luxeestates.netlify.app/',
    tagline: 'Premium property. Premium digital experience.',
    tags: ['REAL ESTATE', 'PREMIUM UI'],
    desc: 'High-end real estate listings with interactive galleries, virtual tour integration, and a luxury-first aesthetic.',
    challenge: 'Most real estate sites prioritise quantity over quality of presentation. Luxeestates needed to position as the premium Nairobi alternative.',
    solution: 'Full-screen photography, a curated listing format, and a map-based search with custom markers. Integrated with their existing CRM.',
    results: ['Avg time on site increased to 6.5 minutes', 'Inquiry submissions up 80%', 'Positioned as top-tier agency in market'],
    tech: ['Next.js', 'Mapbox GL', 'Prisma', 'PostgreSQL', 'Cloudinary'],
    year: '2024',
    category: 'Website',
    color: '#1a1a0a',
  },
  {
    slug: 'aether-weather',
    name: 'Aether Weather',
    url: 'https://aethereather.netlify.app/',
    tagline: 'Live meteorological data, beautifully rendered.',
    tags: ['API INTEGRATION', 'REAL-TIME', 'LIVE DATA'],
    desc: 'A sleek weather interface that fetches live meteorological data globally, with dynamic backgrounds driven by real conditions.',
    challenge: 'Weather apps are either data-heavy and ugly, or pretty and useless. The challenge was building something genuinely useful that felt like art.',
    solution: 'Real-time OpenWeatherMap integration with a generative background system — gradients and colour palettes driven entirely by live weather data.',
    results: ['4.9/5 rating on Product Hunt launch', '12,000 active users in first 6 weeks', 'Featured in CSS Design Awards'],
    tech: ['React', 'TypeScript', 'OpenWeatherMap API', 'Canvas API'],
    year: '2023',
    category: 'Web Application',
    color: '#0a1a2a',
  },
  {
    slug: 'velora-analytics',
    name: 'Velora Analytics',
    url: 'https://velora-saas-analytics-dashboard.netlify.app/',
    tagline: 'Data that tells a story, not just numbers.',
    tags: ['SAAS', 'DASHBOARD', 'DATA VIZ'],
    desc: 'A modern analytics dashboard for SaaS products, visualising key metrics in a clean, dark-mode interface.',
    challenge: 'The client used 4 different tools to track their SaaS metrics — churning through exports and manual compilation every Monday morning.',
    solution: 'A unified dashboard with real-time charts, cohort analysis, and a custom metric builder. White-label ready.',
    results: ['Reporting time cut from 3 hours to 15 minutes', 'Shipped to 200 beta users in 6 weeks', '40% beta-to-paid conversion'],
    tech: ['Next.js', 'Recharts', 'Prisma', 'tRPC', 'Tailwind CSS'],
    year: '2024',
    category: 'SaaS Product',
    color: '#0a0a2a',
  },
  {
    slug: 'progress-logic',
    name: 'Progress Logic',
    url: 'https://shaaas.github.io/experimental-portal-progress/',
    tagline: 'Project metrics, visualised with precision.',
    tags: ['WEB UTILITY', 'DATA UI', 'JAVASCRIPT'],
    desc: 'A specialised portal for capturing and visualising project metrics for a construction and engineering consultancy.',
    challenge: 'The firm tracked project progress in spreadsheets, making it nearly impossible to spot delays or communicate status in real time.',
    solution: 'A custom portal with Gantt-style progress bars, milestone tracking, and client-facing status dashboards.',
    results: ['Project delays identified 2 weeks earlier', 'Completely eliminated weekly status emails', 'Client satisfaction scores improved significantly'],
    tech: ['JavaScript', 'D3.js', 'Express', 'MongoDB', 'Chart.js'],
    year: '2023',
    category: 'Web Application',
    color: '#1a0a2a',
  },
  {
    slug: 'liyai-maina',
    name: 'Liyai Maina',
    url: 'https://mainaliyai.netlify.app/',
    tagline: 'A portfolio as bold as the person behind it.',
    tags: ['PORTFOLIO', 'HTML', 'CSS'],
    desc: 'A personal portfolio built with precision and intent — clean structure, bold typography, crafted to leave a lasting professional impression.',
    challenge: 'The client needed a portfolio to stand out to international creative agencies. Generic templates were not an option.',
    solution: 'Fully custom design with a strong typographic system, subtle animations, and case study format that positioned the work in narrative context.',
    results: ['3 international client inquiries within 2 weeks', 'Featured by a design community newsletter', 'Used as a reference site by 2 other designers'],
    tech: ['HTML5', 'CSS3', 'JavaScript', 'GSAP'],
    year: '2023',
    category: 'Portfolio',
    color: '#0a1a0a',
  },
];